# Generated by Django 4.2.4 on 2023-09-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('create', 'body')},
        ),
    ]
